"""Create IAM accounts, organizations, memberships, and invitations."""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="tenant_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_tenants_name_nonempty"),
        sa.CheckConstraint("slug = lower(slug) AND btrim(slug) <> ''", name="ck_tenants_slug"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="user_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("is_candidate", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(email) <> ''", name="ck_users_email_nonempty"),
        sa.CheckConstraint("btrim(full_name) <> ''", name="ck_users_full_name_nonempty"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "users_email_ci_uq", "users", [sa.literal_column("lower(btrim(email))")], unique=True
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "recruiter", name="membership_role"),
            server_default="recruiter",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="membership_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_memberships_tenant_id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_memberships_tenant_user"),
    )
    op.create_index(
        "memberships_user_idx", "tenant_memberships", ["user_id", "status"], unique=False
    )
    op.create_table(
        "tenant_invitations",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("invited_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "revoked", "expired", name="invitation_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'accepted') = (accepted_by_user_id IS NOT NULL AND accepted_at IS NOT NULL)",
            name="ck_invitations_accepted",
        ),
        sa.CheckConstraint("btrim(email) <> ''", name="ck_invitations_email_nonempty"),
        sa.CheckConstraint(
            "status = 'accepted' OR (accepted_by_user_id IS NULL AND accepted_at IS NULL)",
            name="ck_invitations_unaccepted",
        ),
        sa.CheckConstraint("expires_at > created_at", name="ck_invitations_expiry"),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "invited_by_membership_id"],
            ["tenant_memberships.tenant_id", "tenant_memberships.id"],
            name="fk_invitations_inviter_membership",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "invitations_pending_email_uq",
        "tenant_invitations",
        ["tenant_id", sa.literal_column("lower(btrim(email))")],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )


def downgrade() -> None:
    op.drop_table("tenant_invitations")
    op.drop_table("tenant_memberships")
    op.drop_table("users")
    op.drop_table("tenants")
    for name in (
        "invitation_status",
        "membership_status",
        "membership_role",
        "user_status",
        "tenant_status",
    ):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
